Fix AttributeError in metapath.get_unicode_str()
https://github.com/dhimmel/hetio/commit/9dc747b8fc4e23ef3437829ffde4d047f2e1bdde
broke get_unicode_str for metapaths whose names did not contain a name attribute.

Fixes: AttributeError: 'MetaNode' object has no attribute 'name'